Add dependencies print for Quarkus added artifacts
quarkus-qe/quarkus-utilities pull request #2
Opened 2023-10-10 09:57 UTC by gtroitsk

This PR extends current RHBQ artifact diff job with dependencies print of added/new artifacts. This Java program will be used in Jenkins job later.
After running program `mvn clean install exec:java -Dquarkus.maven.dir="path_to_dir" -Dquarkus.new-artifacts-list="added_artifacts.txt"`, the result is saved to file added_artifacts_deps.txt

2023-10-11 20:16 UTC, mjurc requested changes
I can't get this to work.

I've tested this with 3.2.6.CR1 - https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/view/all/job/rhbq-platform-quarkus-maven-repo-gav-diff/18/artifact/artifacts_3.2.6.CR1_ADDED.txt - this is the added artifact list. The Maven repository zip used can be found in that run's parameters:

```
mvn clean install exec:java -Dquarkus.new-artifacts-list=/home/mjurc/Documents/quarkus-utilities/diff-utils/artifacts_3.2.6.CR1_ADDED.txt -Dquarkus.maven.dir=/home/mjurc/Downloads/rh-quarkus-platform-3.2.6.GA-maven-repository/maven-repository
```

yielded an empty file, so did

```
mvn clean install exec:java -Dquarkus.new-artifacts-list=/home/mjurc/Documents/quarkus-utilities/diff-utils/artifacts_3.2.6.CR1_ADDED.txt -Dquarkus.maven.dir=/home/mjurc/Downloads/rh-quarkus-platform-3.2.6.GA-maven-repository/maven-repository
```

Maybe you could prepare a Jenkins job where it would work, @gtroitsk ? You can take https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/view/all/job/rhbq-platform-quarkus-maven-repo-gav-diff/18/ as baseline.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/src/main/java/org/quarkus/qe/AddedArtifactsPrint.java
> +package org.quarkus.qe;
Let's go with `io.quarkus.qe` package name, as we do for our framework/test suite/etc.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/src/main/java/org/quarkus/qe/Artifact.java
> +package org.quarkus.qe;
Let's go with `io.quarkus.qe` package name, as we do for our framework/test suite/etc.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/src/main/java/org/quarkus/qe/Coordinates.java
> +package org.quarkus.qe;
Let's go with `io.quarkus.qe` package name, as we do for our framework/test suite/etc.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/src/main/java/org/quarkus/qe/Main.java
> +package org.quarkus.qe;
Let's go with `io.quarkus.qe` package name, as we do for our framework/test suite/etc.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/src/main/java/org/quarkus/qe/MavenRepo.java
> +package org.quarkus.qe;
Let's go with `io.quarkus.qe` package name, as we do for our framework/test suite/etc.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/src/main/java/org/quarkus/qe/VersionedCoordinates.java
> +package org.quarkus.qe;
Let's go with `io.quarkus.qe` package name, as we do for our framework/test suite/etc.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/pom.xml
> +    <groupId>org.quarkus.qe</groupId>
Let's go with `io.quarkus.qe` package name, as we do for our framework/test suite/etc.

2023-10-11 20:16 UTC, mjurc commented on diff-utils/pom.xml
> +    <artifactId>added-artifacts</artifactId>
`diff-utils` maybe? Added artifacts seems a little too specific :]

2023-10-11 20:16 UTC, mjurc commented on README.md
> +`mvn clean install exec:java -Dquarkus.maven.dir="path_to_dir" -Dquarkus.new-artifacts-list="added_artifacts.txt"`
This is a good first step, but imho this should be integrated into the diff script later on - the colourful diff after all is where we want to have the dependencies shown.

2023-10-13 15:56 UTC, gtroitsk commented on diff-utils/pom.xml
> +    <artifactId>added-artifacts</artifactId>
Changed

2023-10-13 16:06 UTC, gtroitsk commented on README.md
> +`mvn clean install exec:java -Dquarkus.maven.dir="path_to_dir" -Dquarkus.new-artifacts-list="added_artifacts.txt"`
Ok, I will adjust README to use single script as I have implementation for extended color diff.  This PR only prints dependencies of new artifact in simple text format.
Please see https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/view/utils/job/utils-quarkus-maven-repo-gav-diff-gtroitsk/20/artifact/artifacts_3.2.6.CR1_ADDED.txt

2023-10-24 22:23 UTC, mjurc commented
Hey, I see you've updated the other items - but can you describe what you ran this script with? I cannot figure that step out at all, see https://github.com/quarkus-qe/quarkus-utilities/pull/2#pullrequestreview-1672374252 - can you address that? Thanks!

2023-10-25 11:24 UTC, gtroitsk commented
I use the list of added artifacts in format of groupId:artifactId ($GA in Jenkins script) without versions etc and pass it as a property `quarkus.new-artifacts-list` to Java program.
You can see added_artifacts_list.txt in the job configuration script: https://main-jenkins-csb-quarkusqe.apps.ocp-c1.prod.psi.redhat.com/view/utils/job/utils-quarkus-maven-repo-gav-diff-gtroitsk/configure

2023-10-25 19:15 UTC, mjurc commented
Oh, that report looks correct. I think we can merge this as first step. Thank you!

The next steps:
1. create a script in this repo to run this new Maven project with the outputs of the other script from the existing diff job (or integrate it there)
2. add this dependency info into the colourful diff - make the added dependencies clickable and show/hide what brings them in on click

2023-10-25 19:16 UTC, mjurc approved these changes

2023-10-25 19:16 UTC, merged